# Generated by Django 4.2.7 on 2024-04-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_detalleventa_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoriaEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, unique=True)),
                ('id_categoria_etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.categoriaetiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoSubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.producto')),
                ('id_sub_categoria_etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.subcategoriaetiqueta')),
            ],
        ),
    ]
