# Generated by Django 4.2.9 on 2024-04-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_categoriaetiqueta_subcategoriaetiqueta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoriaetiqueta',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
    ]
